apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  description: Scates
  tags:
    - go
  links:
    - url: https://github.com/shukibakbuki/scates
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: audio-playback
